--DIRECTORUL CU CALEA CATRE CONTAINER
CREATE OR REPLACE DIRECTORY DOC_DIR AS '/opt/oracle/doc_files';
GRANT READ, WRITE ON DIRECTORY DOC_DIR TO user1;
/

--CREEARE TABEL DOCUMENTE
CREATE TABLE documente_word(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume_fisier VARCHAR2(255),
    fisier_binar BLOB,
    continut_text CLOB,
    embedding_vector VECTOR(384)
);
/

--INCARCARE MODEL
--docker cp C:\oracle_files\model.onnx b7d4ff3e0677:/opt/oracle/doc_files/model.onnx
BEGIN
    DBMS_VECTOR.LOAD_ONNX_MODEL(
        directory  => 'MODEL_DIR',
        file_name  => 'model.onnx',
        model_name => 'doc_model',
        metadata   => JSON('{
            "function": "embedding",
            "embeddingOutput": "embedding",
            "input": {"input": ["DATA"]}
        }')
    );
END;
/

--ÎNCARCAREA FISIERULUI BINAR (DOCX) IN TABEL
DECLARE
    v_blob  BLOB;
    v_bfile BFILE := BFILENAME('DOC_DIR', 'test.docx');
BEGIN
    INSERT INTO documente_word (nume_fisier, fisier_binar)
    VALUES ('test.docx', EMPTY_BLOB())
    RETURNING fisier_binar INTO v_blob;

    DBMS_LOB.FILEOPEN(v_bfile, DBMS_LOB.FILE_READONLY);
    DBMS_LOB.LOADFROMFILE(
        dest_lob => v_blob,
        src_lob  => v_bfile,
        amount   => DBMS_LOB.GETLENGTH(v_bfile)
    );
    DBMS_LOB.FILECLOSE(v_bfile);

    COMMIT;
END;
/

-- EXTRAGERE TEXT DIN DOCX 
DECLARE
    v_clob CLOB;
BEGIN
    FOR r IN (
        SELECT id, fisier_binar
        FROM documente_word
        WHERE nume_fisier = 'test.docx'
    ) LOOP
        DBMS_LOB.CREATETEMPORARY(v_clob, TRUE);

        CTX_DOC.IFILTER(r.fisier_binar, v_clob);

        UPDATE documente_word
        SET continut_text = v_clob
        WHERE id = r.id;
    END LOOP;

    COMMIT;
END;
/

--GENERARE VECTOR
UPDATE documente_word
SET embedding_vector = VECTOR_EMBEDDING(doc_model USING continut_text AS DATA)
WHERE nume_fisier = 'test.docx';
/

--QUERY 1 - COMPARA TOATE DOCUMENTELE INTRE ELE
SELECT a.nume_fisier AS document_1,
       b.nume_fisier AS document_2,

       VECTOR_DISTANCE(
           a.embedding_vector,
           b.embedding_vector,
           COSINE
       ) AS scor,

       CASE
           WHEN VECTOR_DISTANCE(a.embedding_vector,b.embedding_vector,COSINE) = 0
                THEN 'Identice semantic'

           WHEN VECTOR_DISTANCE(a.embedding_vector,b.embedding_vector,COSINE) < 0.03
                THEN 'Aproape identice'

           WHEN VECTOR_DISTANCE(a.embedding_vector,b.embedding_vector,COSINE) < 0.10
                THEN 'Foarte similare'

           WHEN VECTOR_DISTANCE(a.embedding_vector,b.embedding_vector,COSINE) < 0.18
                THEN 'Similare'

           WHEN VECTOR_DISTANCE(a.embedding_vector,b.embedding_vector,COSINE) < 0.28
                THEN 'Slab similare'

           WHEN VECTOR_DISTANCE(a.embedding_vector,b.embedding_vector,COSINE) < 0.40
                THEN 'Diferite'

           ELSE 'Foarte diferite'
       END AS interpretare

FROM documente_word a
JOIN documente_word b
ON a.id < b.id
ORDER BY scor;
/

--QUERY 2 - CELE MAI APROPIATE DOCUMENTE DE CATRE UN ANUMIT DOCUMENT
SELECT b.nume_fisier AS document_similar,

       VECTOR_DISTANCE(
           a.embedding_vector,
           b.embedding_vector,
           COSINE
       ) AS scor,

       CASE
           WHEN VECTOR_DISTANCE(a.embedding_vector,b.embedding_vector,COSINE) = 0
                THEN 'Identice semantic'

           WHEN VECTOR_DISTANCE(a.embedding_vector,b.embedding_vector,COSINE) < 0.03
                THEN 'Aproape identice'

           WHEN VECTOR_DISTANCE(a.embedding_vector,b.embedding_vector,COSINE) < 0.10
                THEN 'Foarte similare'

           WHEN VECTOR_DISTANCE(a.embedding_vector,b.embedding_vector,COSINE) < 0.18
                THEN 'Similare'

           WHEN VECTOR_DISTANCE(a.embedding_vector,b.embedding_vector,COSINE) < 0.28
                THEN 'Slab similare'

           WHEN VECTOR_DISTANCE(a.embedding_vector,b.embedding_vector,COSINE) < 0.40
                THEN 'Diferite'

           ELSE 'Foarte diferite'
       END AS interpretare

FROM documente_word a
JOIN documente_word b
ON a.id <> b.id
WHERE a.nume_fisier = 'nume_fisier.docx'
ORDER BY scor
FETCH FIRST 5 ROWS ONLY;
/











